# Generated by Django 5.2 on 2025-10-19 05:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Plantas",
            fields=[
                ("id_planta", models.AutoField(primary_key=True, serialize=False)),
                ("nombre_comun", models.CharField(max_length=100)),
                (
                    "nombre_cientifico",
                    models.CharField(blank=True, max_length=150, null=True),
                ),
                ("familia", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "region_origen",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("rareza", models.CharField(blank=True, max_length=50, null=True)),
                ("descripcion", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Usuarios",
            fields=[
                ("id_usuario", models.AutoField(primary_key=True, serialize=False)),
                ("nombre_usuario", models.CharField(max_length=100)),
                ("correo_electronico", models.CharField(max_length=100, unique=True)),
                ("contrasena_usuario", models.CharField(max_length=255)),
                ("edad", models.IntegerField(blank=True, null=True)),
                (
                    "telefono_celular",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("rol", models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Etapas",
            fields=[
                ("id_etapa", models.AutoField(primary_key=True, serialize=False)),
                (
                    "nombre_etapa",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("descripcion", models.TextField(blank=True, null=True)),
                ("edad_planta", models.IntegerField(blank=True, null=True)),
                ("orden", models.IntegerField(blank=True, null=True)),
                (
                    "id_planta",
                    models.ForeignKey(
                        db_column="id_planta",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="bitacora.plantas",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Registros",
            fields=[
                ("id_registro", models.AutoField(primary_key=True, serialize=False)),
                ("altura_cm", models.FloatField(blank=True, null=True)),
                ("hojas", models.IntegerField(blank=True, null=True)),
                ("luz_horas", models.FloatField(blank=True, null=True)),
                ("fecha_registro", models.DateField(blank=True, null=True)),
                (
                    "id_planta",
                    models.ForeignKey(
                        db_column="id_planta",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="bitacora.plantas",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="plantas",
            name="id_usuario",
            field=models.ForeignKey(
                db_column="id_usuario",
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="bitacora.usuarios",
            ),
        ),
        migrations.CreateModel(
            name="Experimentos",
            fields=[
                ("id_experimento", models.AutoField(primary_key=True, serialize=False)),
                ("descripcion", models.TextField(blank=True, null=True)),
                ("fecha_inicio", models.DateField(blank=True, null=True)),
                ("fecha_fin", models.DateField(blank=True, null=True)),
                (
                    "id_planta",
                    models.ForeignKey(
                        db_column="id_planta",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="bitacora.plantas",
                    ),
                ),
                (
                    "id_usuario",
                    models.ForeignKey(
                        db_column="id_usuario",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="bitacora.usuarios",
                    ),
                ),
            ],
        ),
    ]
